### ISSUE TITLE
changing timezone in iOS does not trigger an event

### ISSUE THREAD

**Issue by ristiisa** [sikandernoori/time_change_detector#1]
Changing timezone in iOS does not trigger an event.

```
iOS 15.1 19B74
Flutter 2.8.1 (stable)
```

**Comment by sikandernoori** [comment]
@ristiisa are you running example app ?

if not can you please check IOS settings.

**Comment by sikandernoori** [comment]
@ristiisa Please use the latest version (0.0.2) timezone event added.

**Comment by ristiisa** [comment]
new version fixed the issue, thanks
