### ISSUE TITLE
Feature request system settings 12/24 hour format

### ISSUE THREAD

**Issue by offline-first** [sikandernoori/time_change_detector#7]
Is it also possible to get changes to the 12/24 hour format?

**Comment by sikandernoori** [comment]
**[Out of scope]**

purpose of this plugin is to detect change in, `Time`, `Time Zone` or `Date`.

However what you require is also possible in `Android` directly by getting previous value from intent 

`long previousTimeMillis = intent.getLongExtra("previousTime", -1);`

but for IOS you will have to use timer to check every `n` seconds based on your requirement.
